#!/usr/bin/env bash
set -e
apt-get update
apt-get install -y swig

pip3 install --upgrade pip
pip install toml
pip install numpy
pip3 install torch torchvision torchaudio
pip install gym'[box2d]'
pip install tqdm
pip install gym==0.24.0
pip install gym-notices==0.0.7
pip install scikit-learn
pip install numpy==1.26.4
pip install matplotlib